language: ruby
rvm:
  - 2.6.5
services:
  - postgresql
install: bundle install
branches:
  only:
  - /.*/
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
