language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
addons:
  postgresql: 11.3
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
before_install:
  # stop old version
  - sudo /etc/init.d/postgresql stop
  - gem update --system
  - gem install bundler:2.0.2
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database tracis_ci_test;' -U postgres
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec