language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
addons:
  postgresql: "11.3"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - gem update --system
  - gem install bundler:2.0.2
before_script:
  - psql --version
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database tracis_ci_test;' -U postgres
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec