language: ruby
rvm:
  - 2.6.0
addons:
  postgresql: 11.3
before_install:
  - gem update --system
  - gem install bundler:2.0.2
script:
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec